<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>get ML output</name>
  <uuid>79e6750a-eaf5-4e80-96b8-c9cb4a4640f6</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if the predicted clientdefaultedpayment is "TRUE"
then
set decision to a new Scoreboard where 
	High risk is true,
	the Confidence is the confidence,
	the Segment is "Unknown";
else
set decision to a new Scoreboard where 
	the Confidence is the confidence , 
	the Segment is "Unknown" , 
	High risk is false;  ]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
